### ISSUE TITLE
No clear instructions on how to use rules

### ISSUE THREAD

**Issue by Dalia-Siblini** [dustinlacewell/matched-line-dimmer-vsix#2]
In the Readme file, you specified that:

> Rules
> 
> An array of objects with the following attributes:
> 
> One of:
> 
>     pattern: A single regex pattern
>     patterns: An array of regex patterns
> 
> And one of (or both):
> 
>     extensions: An array of file-extensions
>     languages: An array of language identifiers

Can you please give some examples on the syntax? 
I'm not sure how to implement it. I tried the following combinations, but they did not seem to work:

- ["pattern, extension"]
- ["pattern", "extension"]
- ["pattern", "language"]
- [["pattern"], ["extension"]]

note that i'm writing these settings in the settings.json file in VSCode

Thanks!

**Comment by dustinlacewell** [comment]
An array of these:

```ts
export type DimmingRule = {
	pattern?: string;
	patterns?: string[];

	extensions?: string[];
	languages?: string[];
};
```

https://github.com/dustinlacewell/matched-line-dimmer-vsix/blob/main/src/DimmingRule.ts
